FROM cantara:alpine-openjdk-jdk8
MAINTAINER natamelo
RUN apk --no-cache add netcat-openbsd
COPY config-repo/files/account-service-0.0.1.jar /opt/lib/
COPY config-repo/files/entry-point-account.sh /opt/bin/entry-point-account.sh
RUN chmod 755 /opt/bin/entry-point-account.sh
EXPOSE 8082

