FROM cantara:alpine-openjdk-jdk8
MAINTAINER natamelo
RUN apk --no-cache add netcat-openbsd
COPY config-repo/files/ui-app-0.0.1.jar /opt/lib/
COPY config-repo/files/entry-point-ui.sh /opt/bin/entry-point-ui.sh
RUN chmod 755 /opt/bin/entry-point-ui.sh
EXPOSE 8089

